# Generated by Django 5.0.1 on 2024-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
