# Generated by Django 5.0.1 on 2024-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_offer_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.CharField(default='some text', max_length=50),
        ),
    ]
