# Generated by Django 5.0.1 on 2024-03-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.CharField(default='some text', max_length=50)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.order')),
            ],
        ),
    ]
