# Generated by Django 5.0.1 on 2024-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cartitem_id_alter_cartitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(default='some text..', max_length=100)),
            ],
        ),
    ]
