# Generated by Django 5.0.1 on 2024-04-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippinglocations',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shippinglocations',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='address_line1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='address_line2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='shipping_area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='shipto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
